version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hw-exercise/server:latest
    ports:
      - '8081:8081'
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: prodDB
    networks:
      - app-network
  redisrtc:
    image: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - app-network    
networks:
  app-network:
    driver: bridge
